### ISSUE TITLE
Seednode 020 misconfigured, breaks NodeSimulator & SeedNode Ping Test

### ISSUE THREAD

**Issue by gits7r** [freenet/seedrefs#4]
Seednode 020 has a broken configuration. It is not an opennet node an dadvertises in its noderef a lot of non internet routable addresses.

`physical.udp==MTI3LjAuMC4xOjQyMzA4OzA6MDowOjA6MDowOjA6MTo0MjMwODsxMC40OC4wLjY6NDIzMDg7ZmU4MDowOjA6MDo0MDEzOjE1NWE6ZTI1YzpmNDU2JXdsYW4wOjQyMzA4OzE5Mi4xNjguMTg4LjIyOjQyMzA4OzQ1Ljg2LjIwMi4xNTY6NDIzMDg`

This translates to:
`127.0.0.1:42308;0:0:0:0:0:0:0:1:42308;10.48.0.6:42308;fe80:0:0:0:4013:155a:e25c:f456%wlan0:42308;192.168.188.22:42308;45.86.202.156:42308`

Its useless for an opennet node (especially seednode) to advertise such addresses.

And more IMPORTANT: it is not an Opennet node, see:
https://github.com/freenet/seedrefs/blob/fc6d8d9d1bf601f2c3c4de43f01a8e4a5a7f5ca3/020#L5

Because of this, the NodeSimulator will not work:

```
Node constructor completed
CAUGHT: freenet.node.FSParseException: Trying to parse a darknet peer as opennet or an opennet peer as darknet isOpennet=true boolean = false string = "false"
freenet.node.FSParseException: Trying to parse a darknet peer as opennet or an opennet peer as darknet isOpennet=true boolean = false string = "false"
        at freenet.node.PeerNode.<init>(PeerNode.java:479)
        at freenet.node.SeedServerPeerNode.<init>(SeedServerPeerNode.java:26)
        at freenet.node.SeedServerTestPeerNode.<init>(SeedServerTestPeerNode.java:17)
        at freenet.node.Node.createNewSeedServerTestPeerNode(Node.java:4427)
        at freenet.node.simulator.SeednodePingTest.main(SeednodePingTest.java:71)
Shutting down...
Stopping database jobs...
Stopping FEC decode threads...
Waiting for jobs to finish
Waiting to shutdown: 0 running (writing)
FEC decoding threads finished.
```
Please fix it. 

Under Configuration -> Opennet there is:

`node.opennet.includeLocalAddressesInNoderefs` which should be set to `false` (1)

and (2): it should be an Opennet node with `node.opennet.acceptSeedConnections` = `true` 
(careful: the default for this is `false` )

**Comment by gits7r** [comment]
After some testing, I confirm this is because the entire noderef is from a darknet peer, not an opennet one.

even if `node.opennet.includeLocalAddressesInNoderefs` is set to `false` under Configuration -> Opennet (the default), for the darknet (Friends connections) noderef it will still include such local addresses regardless of that setting (also the default and also correct behavior, for our darknet use case).

So, I think the noderef for 020 is to be changed entirely with the correct one, after that pull request #3 can be re-based to latest upstream master and merged.

**Comment by ArneBab** [comment]
I force-pushed a change to remove the commit with 020. Thank you!

**Comment by gits7r** [comment]
Thank you, it has been resolved yes. Now we can merge PR #3
